# Generated by Django 3.2.5 on 2021-07-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_user_access_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueTrack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='device_id',
            field=models.CharField(default='f9aeb39f36a9bfcb4fb49b8ee12b319471aacc08', max_length=50, verbose_name='device_id'),
            preserve_default=False,
        ),
    ]
