# Generated by Django 3.2.5 on 2021-07-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210711_0933'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QueueTrack',
        ),
        migrations.AlterField(
            model_name='user',
            name='refresh_token',
            field=models.CharField(max_length=250, verbose_name='refresh_token'),
        ),
    ]
