# Generated by Django 3.2.5 on 2021-07-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210713_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
