# Generated by Django 3.2.5 on 2021-07-16 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0001_initial'),
        ('backend', '0010_alter_lobby_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lobby_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lobby.lobby'),
        ),
        migrations.DeleteModel(
            name='Lobby',
        ),
    ]
