# Generated by Django 3.2.5 on 2021-07-19 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0003_lobby_max_members'),
        ('backend', '0011_auto_20210716_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lobby_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lobby.lobby'),
        ),
    ]
