# Generated by Django 3.2.5 on 2021-07-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='num_members',
            field=models.PositiveIntegerField(default=1, verbose_name='num_members'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lobby',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
