# Generated by Django 3.2.5 on 2021-07-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0003_lobby_max_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='settings',
            field=models.JSONField(default={'ban_list': [], 'max_members': 5, 'num_members': 1}),
        ),
    ]
