# Generated by Django 3.2.5 on 2021-07-23 10:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lobby', '0004_lobby_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='ban_list',
            field=models.ManyToManyField(related_name='ban', to=settings.AUTH_USER_MODEL),
        ),
    ]
