# Generated by Django 3.2.5 on 2021-08-06 09:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0006_alter_lobby_ban_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
