# Generated by Django 3.2.5 on 2021-08-06 10:17

from django.db import migrations
import shortuuid.main
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0009_alter_lobby_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
