# Generated by Django 3.2.5 on 2021-08-06 10:49

from django.db import migrations
import lobby.models
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0011_alter_lobby_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default=lobby.models._get_short_uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
