# Generated by Django 3.2.5 on 2021-08-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0012_alter_lobby_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='password',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
    ]
