# Generated by Django 3.2.5 on 2021-08-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0013_lobby_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='password',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
